export {
  config,
  defineField,
  val,
  type DefineFieldOptions,
  type Field,
  type FieldDescriptor,
  type FieldOptions,
  type FieldTemplate,
  type FieldValue,
  type JsonValue,
  type Vector2,
  type Vector3,
} from './authoring-core';
export type {
  EditorFieldComponent,
  EditorFieldComponentProps,
} from './ui/sdk';

export {
  array,
  boolean,
  color,
  euler,
  fileUrl,
  json,
  number,
  object,
  optional,
  position3D,
  schema,
  string,
  transform3D,
  vec2,
  vec3,
  type ArrayFieldOptions,
  type BooleanFieldOptions,
  type ColorFieldOptions,
  type FileUrlFieldOptions,
  type NumberFieldOptions,
  type ObjectFieldOptions,
  type OptionalFieldOptions,
  type StringFieldOptions,
  type Transform3D,
  type Transform3DFieldOptions,
  type VectorFieldOptions,
} from './default-schemas';
