import { css } from '@emotion/css';
import { defaultTheme } from '@iwe/ui';

const t = defaultTheme;

export const styles = {
  shell: css({
    position: 'relative',
    height: '100%',
    width: '100%',
    background: '#ffffff',
    color: '#09090b',
    fontFamily: t.font.sans,
    fontSize: 13,
  }),
  configError: css({ color: '#b42318', fontSize: 12, padding: '8px 0' }),
  configInput: css({
    width: '100%',
    boxSizing: 'border-box',
    border: '1px solid #e4e4e7',
    background: '#ffffff',
    color: '#09090b',
    borderRadius: 4,
    font: 'inherit',
    fontSize: 12,
    padding: '6px 7px',
    '&:focus': { outline: '2px solid rgba(9, 9, 11, 0.08)', borderColor: '#d4d4d8' },
  }),
  configVector: css({ display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0, 1fr))', gap: 4 }),
  configVector2: css({ gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' }),
  configJson: css({ display: 'grid', gap: 6 }),
  configTextarea: css({
    width: '100%',
    boxSizing: 'border-box',
    minHeight: 92,
    resize: 'vertical',
    border: '1px solid #e4e4e7',
    background: '#ffffff',
    color: '#09090b',
    borderRadius: 4,
    font: 'inherit',
    fontFamily: t.font.mono,
    fontSize: 12,
    padding: '6px 7px',
    '&:focus': { outline: '2px solid rgba(9, 9, 11, 0.08)', borderColor: '#d4d4d8' },
  }),
  configButton: css({
    justifySelf: 'end',
    border: '1px solid #e4e4e7',
    background: '#ffffff',
    color: '#09090b',
    borderRadius: 4,
    font: 'inherit',
    fontSize: 12,
    padding: '5px 9px',
    cursor: 'pointer',
    '&:hover': { background: '#f4f4f5' },
    '&:disabled': { cursor: 'not-allowed', color: '#a1a1aa', background: '#fafafa' },
  }),
  configCustomField: css({ minWidth: 0 }),
  configMissingField: css({ color: '#52525b', fontSize: 12 }),
  iframe: css({ width: '100%', height: '100%', border: 'none', background: '#ffffff', display: 'block' }),
  slotBody: css({ width: '100%', height: '100%', minWidth: 0, minHeight: 0, overflow: 'hidden', background: '#ffffff' }),
  paletteBackdrop: css({
    position: 'fixed',
    inset: 0,
    background: 'rgba(17, 24, 39, 0.22)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingTop: '18vh',
    zIndex: 1000,
    backdropFilter: 'blur(2px)',
  }),
  palette: css({
    width: 'min(560px, 92vw)',
    background: '#ffffff',
    border: '1px solid #d4d4d8',
    borderRadius: 10,
    boxShadow: '0 10px 32px -12px rgba(9, 9, 11, 0.18), 0 2px 6px rgba(9, 9, 11, 0.06)',
    overflow: 'hidden',
  }),
  paletteInput: css({
    width: '100%',
    boxSizing: 'border-box',
    border: 0,
    padding: '14px 16px',
    font: 'inherit',
    fontSize: 14,
    background: 'transparent',
    color: '#09090b',
    outline: 'none',
    borderBottom: '1px solid #e4e4e7',
    '&::placeholder': { color: '#a1a1aa' },
  }),
  paletteList: css({ maxHeight: '48vh', overflowY: 'auto', padding: '6px 0' }),
  paletteEmpty: css({ padding: '14px 16px', color: '#52525b', fontSize: 13 }),
  paletteItem: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 14px',
    cursor: 'pointer',
    color: '#09090b',
    fontSize: 13,
    outline: 'none',
    '&[data-selected="true"]': { background: '#f4f4f5' },
  }),
  paletteItemTitle: css({ flex: '1 1 auto' }),
  paletteItemHint: css({
    fontFamily: t.font.mono,
    fontSize: 11,
    color: '#52525b',
    background: '#fafafa',
    padding: '1px 6px',
    borderRadius: 3,
    border: '1px solid #e4e4e7',
    marginLeft: 12,
  }),
};
