import { css } from '@emotion/css';
import { defaultTheme } from '@immersive-web-editor/ui';

const t = defaultTheme;

export const styles = {
  shell: css({
    position: 'relative',
    height: '100%',
    width: '100%',
    background: '#ffffff',
    color: '#09090b',
    fontFamily: t.font.sans,
    fontSize: 13,
  }),
  hostLayout: css({
    height: '100%',
    width: '100%',
    display: 'grid',
    gridTemplateColumns: '232px minmax(0, 1fr)',
    background: '#ffffff',
    color: '#09090b',
  }),
  hostSidebar: css({
    minWidth: 0,
    minHeight: 0,
    borderRight: '1px solid #e4e4e7',
    background: '#fafafa',
    display: 'grid',
    gridTemplateRows: 'auto auto minmax(0, 1fr) auto',
    gap: 8,
    padding: 10,
  }),
  hostBrand: css({
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    minHeight: 34,
    padding: '0 4px',
    fontWeight: 650,
    color: '#09090b',
  }),
  hostBrandMark: css({
    width: 22,
    height: 22,
    borderRadius: 5,
    background: '#111113',
    color: '#ffffff',
    display: 'grid',
    placeItems: 'center',
    fontSize: 12,
    fontWeight: 700,
  }),
  hostSidebarHeader: css({
    display: 'grid',
    gap: 6,
  }),
  hostSidebarLabel: css({
    padding: '0 4px',
    color: '#71717a',
    fontSize: 11,
    fontWeight: 600,
    textTransform: 'uppercase',
  }),
  hostProjects: css({
    minHeight: 0,
    overflow: 'auto',
    display: 'grid',
    alignContent: 'start',
    gap: 3,
  }),
  hostProjectButton: css({
    width: '100%',
    minWidth: 0,
    height: 32,
    border: 0,
    borderRadius: 6,
    background: 'transparent',
    color: '#3f3f46',
    display: 'grid',
    gridTemplateColumns: '18px minmax(0, 1fr)',
    alignItems: 'center',
    gap: 8,
    padding: '0 8px',
    font: 'inherit',
    fontSize: 12,
    textAlign: 'left',
    cursor: 'pointer',
    '&:hover': { background: '#f4f4f5', color: '#09090b' },
    '&[data-active="true"]': { background: '#ffffff', color: '#09090b', boxShadow: 'inset 0 0 0 1px #e4e4e7' },
    '& svg': { width: 15, height: 15, strokeWidth: 1.9 },
  }),
  hostProjectName: css({ minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }),
  hostSidebarAction: css({
    width: '100%',
    height: 32,
    border: '1px solid #e4e4e7',
    borderRadius: 6,
    background: '#ffffff',
    color: '#09090b',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    font: 'inherit',
    fontSize: 12,
    cursor: 'pointer',
    '&:hover': { background: '#f4f4f5' },
    '&:disabled': { cursor: 'not-allowed', color: '#a1a1aa', background: '#fafafa' },
    '& svg': { width: 14, height: 14, strokeWidth: 2 },
  }),
  hostUserButton: css({
    width: '100%',
    minWidth: 0,
    border: 0,
    borderRadius: 6,
    background: 'transparent',
    color: '#09090b',
    display: 'grid',
    gridTemplateColumns: '28px minmax(0, 1fr) 16px',
    alignItems: 'center',
    gap: 8,
    padding: 6,
    font: 'inherit',
    textAlign: 'left',
    cursor: 'pointer',
    '&:hover, &[data-active="true"]': { background: '#f4f4f5' },
  }),
  hostAvatar: css({
    width: 28,
    height: 28,
    borderRadius: 6,
    background: '#18181b',
    color: '#ffffff',
    display: 'grid',
    placeItems: 'center',
    fontSize: 12,
    fontWeight: 700,
  }),
  hostUserText: css({ minWidth: 0, display: 'grid', gap: 1 }),
  hostUserName: css({ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontSize: 12, fontWeight: 600 }),
  hostUserEmail: css({ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontSize: 11, color: '#71717a' }),
  hostMain: css({ minWidth: 0, minHeight: 0, position: 'relative', overflow: 'hidden' }),
  hostEmptyState: css({
    height: '100%',
    display: 'grid',
    placeItems: 'center',
    background: '#ffffff',
    color: '#3f3f46',
  }),
  hostEmptyPanel: css({
    width: 'min(360px, calc(100% - 48px))',
    display: 'grid',
    gap: 10,
    textAlign: 'center',
    '& h1': { margin: 0, fontSize: 18, letterSpacing: 0, color: '#09090b' },
    '& p': { margin: 0, fontSize: 13, lineHeight: 1.45, color: '#71717a' },
  }),
  authShell: css({
    height: '100%',
    display: 'grid',
    placeItems: 'center',
    background: '#f7f7f8',
    color: '#09090b',
    padding: 20,
  }),
  authPanel: css({
    width: 'min(360px, 100%)',
    border: '1px solid #e4e4e7',
    borderRadius: 8,
    background: '#ffffff',
    boxShadow: '0 16px 40px rgba(17, 17, 19, 0.08)',
    padding: 18,
    display: 'grid',
    gap: 14,
  }),
  authHeading: css({
    display: 'grid',
    gap: 4,
    '& h1': { margin: 0, fontSize: 18, letterSpacing: 0 },
    '& p': { margin: 0, color: '#71717a', fontSize: 13, lineHeight: 1.4 },
  }),
  authForm: css({ display: 'grid', gap: 10 }),
  authField: css({
    display: 'grid',
    gap: 5,
    color: '#3f3f46',
    fontSize: 12,
    fontWeight: 500,
  }),
  authInput: css({
    width: '100%',
    boxSizing: 'border-box',
    border: '1px solid #e4e4e7',
    borderRadius: 6,
    background: '#ffffff',
    color: '#09090b',
    font: 'inherit',
    fontSize: 13,
    minHeight: 34,
    padding: '0 9px',
    '&:focus': { outline: '2px solid rgba(9, 9, 11, 0.08)', borderColor: '#d4d4d8' },
  }),
  authError: css({ color: '#b42318', fontSize: 12, lineHeight: 1.35 }),
  authSwitch: css({
    border: 0,
    background: 'transparent',
    color: '#2563eb',
    font: 'inherit',
    fontSize: 12,
    cursor: 'pointer',
    justifySelf: 'center',
  }),
  accountPage: css({
    height: '100%',
    overflow: 'auto',
    padding: 24,
    background: '#ffffff',
  }),
  accountPanel: css({
    maxWidth: 560,
    display: 'grid',
    gap: 16,
    '& h1': { margin: 0, fontSize: 20, letterSpacing: 0 },
  }),
  accountRows: css({
    border: '1px solid #e4e4e7',
    borderRadius: 8,
    overflow: 'hidden',
  }),
  accountRow: css({
    minHeight: 42,
    display: 'grid',
    gridTemplateColumns: '140px minmax(0, 1fr)',
    alignItems: 'center',
    gap: 12,
    padding: '0 12px',
    borderBottom: '1px solid #e4e4e7',
    fontSize: 13,
    '&:last-child': { borderBottom: 0 },
    '& span:first-child': { color: '#71717a' },
    '& span:last-child': { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  }),
  configError: css({ color: '#b42318', fontSize: 12, padding: '8px 0' }),
  configInput: css({
    width: '100%',
    boxSizing: 'border-box',
    border: '1px solid #e4e4e7',
    background: '#ffffff',
    color: '#09090b',
    borderRadius: 4,
    font: 'inherit',
    fontSize: 12,
    padding: '6px 7px',
    '&:focus': { outline: '2px solid rgba(9, 9, 11, 0.08)', borderColor: '#d4d4d8' },
  }),
  configColor: css({ minHeight: 30, padding: 3 }),
  configToggle: css({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 7,
    minHeight: 28,
    fontSize: 12,
    color: '#09090b',
    cursor: 'pointer',
    '& input': { margin: 0 },
  }),
  configSelect: css({
    width: '100%',
    minWidth: 0,
    boxSizing: 'border-box',
    border: '1px solid #e4e4e7',
    background: '#ffffff',
    color: '#09090b',
    borderRadius: 4,
    font: 'inherit',
    fontSize: 12,
    minHeight: 30,
    padding: '0 28px 0 7px',
    '&:focus': { outline: '2px solid rgba(9, 9, 11, 0.08)', borderColor: '#d4d4d8' },
  }),
  configVector: css({ display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0, 1fr))', gap: 4 }),
  configVector2: css({ gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' }),
  configJson: css({ display: 'grid', gap: 6 }),
  configTextarea: css({
    width: '100%',
    boxSizing: 'border-box',
    minHeight: 92,
    resize: 'vertical',
    border: '1px solid #e4e4e7',
    background: '#ffffff',
    color: '#09090b',
    borderRadius: 4,
    font: 'inherit',
    fontFamily: t.font.mono,
    fontSize: 12,
    padding: '6px 7px',
    '&:focus': { outline: '2px solid rgba(9, 9, 11, 0.08)', borderColor: '#d4d4d8' },
  }),
  configButton: css({
    justifySelf: 'end',
    border: '1px solid #e4e4e7',
    background: '#ffffff',
    color: '#09090b',
    borderRadius: 4,
    font: 'inherit',
    fontSize: 12,
    padding: '5px 9px',
    cursor: 'pointer',
    '&:hover': { background: '#f4f4f5' },
    '&:disabled': { cursor: 'not-allowed', color: '#a1a1aa', background: '#fafafa' },
  }),
  configFileUpload: css({ display: 'grid', gap: 5 }),
  configFileRow: css({ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) auto', gap: 6 }),
  configFileButton: css({
    border: '1px solid #e4e4e7',
    background: '#ffffff',
    color: '#09090b',
    borderRadius: 4,
    font: 'inherit',
    fontSize: 12,
    minHeight: 30,
    padding: '0 9px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    cursor: 'pointer',
    '&:hover': { background: '#f4f4f5' },
    '&[data-disabled="true"]': { cursor: 'not-allowed', color: '#a1a1aa', background: '#fafafa' },
    '& svg': { width: 14, height: 14, strokeWidth: 1.9 },
  }),
  configFileInput: css({ display: 'none' }),
  configFileError: css({ color: '#b42318', fontSize: 11, lineHeight: 1.35 }),
  configCustomField: css({ minWidth: 0 }),
  configMissingField: css({ color: '#52525b', fontSize: 12 }),
  previewFrameSlot: css({ position: 'relative', width: '100%', height: '100%', minWidth: 0, minHeight: 0 }),
  iframe: css({ width: '100%', height: '100%', border: 'none', background: '#ffffff', display: 'block' }),
  previewCanvasLayer: css({
    position: 'relative',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
  }),
  previewCanvasViewport: css({
    position: 'absolute',
    overflow: 'hidden',
  }),
  previewCanvas: css({
    width: '100%',
    height: '100%',
    background: 'transparent',
    display: 'block',
    '& canvas': {
      width: '100% !important',
      height: '100% !important',
      display: 'block',
    },
  }),
  previewLoading: css({
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    display: 'grid',
    placeItems: 'center',
    background: 'rgba(255, 255, 255, 0.76)',
    color: '#52525b',
    pointerEvents: 'none',
  }),
  spinner: css({ animation: 'iwe-spin 900ms linear infinite', '@keyframes iwe-spin': { to: { transform: 'rotate(360deg)' } } }),
  slotBody: css({ width: '100%', height: '100%', minWidth: 0, minHeight: 0, overflow: 'hidden', background: '#ffffff' }),
  paletteBackdrop: css({
    position: 'fixed',
    inset: 0,
    background: 'rgba(17, 24, 39, 0.22)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingTop: '18vh',
    zIndex: 1000,
    backdropFilter: 'blur(2px)',
  }),
  palette: css({
    width: 'min(560px, 92vw)',
    background: '#ffffff',
    border: '1px solid #d4d4d8',
    borderRadius: 10,
    boxShadow: '0 10px 32px -12px rgba(9, 9, 11, 0.18), 0 2px 6px rgba(9, 9, 11, 0.06)',
    overflow: 'hidden',
  }),
  paletteInput: css({
    width: '100%',
    boxSizing: 'border-box',
    border: 0,
    padding: '14px 16px',
    font: 'inherit',
    fontSize: 14,
    background: 'transparent',
    color: '#09090b',
    outline: 'none',
    borderBottom: '1px solid #e4e4e7',
    '&::placeholder': { color: '#a1a1aa' },
  }),
  paletteList: css({ maxHeight: '48vh', overflowY: 'auto', padding: '6px 0' }),
  paletteEmpty: css({ padding: '14px 16px', color: '#52525b', fontSize: 13 }),
  paletteItem: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 14px',
    cursor: 'pointer',
    color: '#09090b',
    fontSize: 13,
    outline: 'none',
    '&[data-selected="true"]': { background: '#f4f4f5' },
  }),
  paletteItemTitle: css({ flex: '1 1 auto' }),
  paletteItemHint: css({
    fontFamily: t.font.mono,
    fontSize: 11,
    color: '#52525b',
    background: '#fafafa',
    padding: '1px 6px',
    borderRadius: 3,
    border: '1px solid #e4e4e7',
    marginLeft: 12,
  }),
};
